Style/AsciiComments:
  Enabled: false

Metrics/LineLength:
  Max: 200

AllCops:
  TargetRubyVersion: 2.3

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Max: 36

Style/MixinUsage:
    Exclude:
    - 'bin/setup'
    - 'bin/update'
Style/ClassAndModuleChildren:
  Exclude:
  - 'test/test_helper.rb'